before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
.before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
.before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
before str.at
terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::at: __n (which is 20) >= this->size() (which is 20)

This application has requested the Runtime to terminate it in an unusual way.
Please contact the application's support team for more information.